name: "Pull request hardware test reminder"
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Post Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Have you performed the necessary hardware test to ensure there are no breaking changes?'
            })
