name: "Pull request hardware test reminder"
on:
  pull_request:

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required
          reminder_message: "Have you the necessary hardware test to ensure there are no breaking changes?"
          review_turnaround_hours: 0
